sudo: required
language: python
services:
- docker
python:
- '3.8'
before_script:
- docker-compose build
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- docker-compose run --rm web bash -c "flake8 . && python wait_for_postgres.py &&
  ./manage.py test"
after_script:
- "./cc-test-reporter format-coverage ./coverage.xml -t coverage.py -p ./icgbooks"
- "./cc-test-reporter upload-coverage"
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
notifications:
  email: false
cache:
  pip: true
env:
  global:
    secure: kS50/umDtdMMQLvkbvF+vQ9iEMKvlNVcOjsS2PAQGkYRty3/GiH/zpbRxJwto/NZoPCJBrZH34NqqUEIEx2f2qfzx+ivvSmbRCyxE0Lc2If8GzUDimU8ndVd7145CBJJSpml3Sj5nepXFKLmuawVDNMxH4k1cwqOudhroaOi7dkNI0loc3jYhpAuP5gpAalVisKC8EjEJUXm8ns9MjSETGoPzpp4yFBjKDzYvo2QnVtAmFoKfKaKgQHmo0Hyb6yjrlk/u7DQWySCOF/bIRIzew2SzwsSZiiwbrlXvCGukpfPBBk5o4Mo7j6OorRkDY4SZ1QDckR+lS3C3xzHxchBfhbTawCxk5JlESLxuRY8OVoEWsXJUR/qBp1/uBc7D0hJXSwO24uAug8Oo3XvipbgCH56U54rIj8m9sWCFlX/S8OR1nKU++14fJYjEbXkQnn0PBnEGndlvk3YUdVOy3rCNSmUrb/KD97ja+5DExTgx19V/xqKYmroAx4sVlm0f6CxOUUEaP1E6++AbSyxnHQh7cfaguOzrbgIv0RJj34l7vj9kTHqWnJeoTSQ0AdIMixWu0pgpXg0g4pA19m6AMJSyNvbQWk0j+Q3zIo3eC3H2RB1D2eT4+bP+ozF49lfDu+UgJ7KKnkGNtJlqPdai7OOk6oxvkh6lAg7WrrqWeCBCeg=
