site_name: icgbooks
site_description: Manage your book reading experience
repo_url: https://github.com/topblossom/ibpy
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/topblossom">topblossom</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
