# Generated by Django 3.0.6 on 2020-05-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_squashed_0003_book'),
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='books',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
    ]
